//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakeemhikmat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int order_detail_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> unit_price { get; set; }
        public Nullable<int> rating { get; set; }
        public string comment { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
